name: Main Branch CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN_PROD }}
        KOSLI_ORG: meekrosoft
      
    steps:
    - uses: actions/checkout@v2

    - name: setup kosli
      uses: kosli-dev/setup-cli-action@v2

    - name: create flow
      run: ./attest-artifacts.sh